services:
  redis:
    image: redis:7.2.4-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_VOLUME}:/data
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8800:80"
    env_file:
      - .env
    volumes:
      - ${PGADMIN_VOLUME}:/var/lib/pgadmin
    depends_on:
      - postgres
  nginx:
    image: nginx:1.25.3
    restart: always
    ports:
      - "${PORT}:80"
    volumes:
      - ./config/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./server/app:/app
      - ${CONFIG_VOLUME}:/etc/traindb/workbench
    depends_on:
      - redis
      - postgres
    command: uvicorn --host=0.0.0.0 --port 3000 main:app --reload
