version: '3.3'

services:
  redis:
    image: redis:7.2.4-alpine
    restart: always
    volumes:
      - ${REDIS_VOLUME}:/data
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${CONFIG_VOLUME}:/etc/traindb/workbench
    depends_on:
      - redis
      - postgres
    command: uvicorn --host=0.0.0.0 --port 4000 main:app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A main worker --loglevel=info
  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
