global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:3000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']